# Site settings
title: Billcountry
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Billcountry Mwaniki
user_description: A software engineer still trying to quit coffee since 2010 but turns out I'm not a quitter.
user_title: Software Engineer
email: me@billcountry.tech
twitter: Billcountry
github:  Billcountry
linkedin:  Billcountry
hackerrank: Billcountry
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
